agent_name: my_first_aea
author: fetchai
version: 0.27.0
description: A simple agent to demo the echo skill.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.21.0
contracts: []
protocols:
- fetchai/default:1.0.0
- fetchai/state_update:1.0.0
- open_aea/signing:1.0.0
skills:
- fetchai/echo:0.19.0
default_connection: fetchai/stub:0.21.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-fetchai:
    version: <2.0.0,>=1.0.0
package_hash: QmS2YHyr9WQFRo6jgxPQkJB2D5851tH55nqbhMTEkisd9G
ipfs:
  connections:
    fetchai/stub:0.21.0:
      hash: QmPuREtoLeFptskYNn24mmFwkgNwqZCA39i2mByD4vVNUK
  protocols:
    fetchai/default:1.0.0:
      hash: QmYjuE4joesaMnVKBBrHosraEYKS7HjeHaApJLfW9NNFtT
    fetchai/state_update:1.0.0:
      hash: QmPTtxV7h696uiUHGXWWTvRqvNeuByCPZwPZWXtxuvVbtS
    open_aea/signing:1.0.0:
      hash: QmNojEWktaeWeSueAUw9pZEprspLoycuBgUjKNGwMkS1vF
  skills:
    fetchai/echo:0.19.0:
      hash: QmeQDhbJhyFsYwsq2a41iv46BQhKf5774ZHfJfFaXrbciR
  contracts: {}
