apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: open-aea
build:
  tagPolicy:
    envTemplate:
      template: "1.14.0"
  artifacts:
  - image: valory/open-aea-develop
    docker:
      dockerfile: develop-image/Dockerfile
      noCache: true

  - image: valory/open-aea-user
    docker:
      dockerfile: user-image/Dockerfile
      noCache: true

  - image: valory/open-aea-deploy
    context: deploy-image
    docker:
      dockerfile: Dockerfile
      noCache: true

profiles:
  - name: docs
    build:
      tagPolicy:
        envTemplate:
          template: "{{.VERSION}}"
      artifacts:
      - image: valory/open-aea-docs
        docker:
          dockerfile: docs-image/Dockerfile
          noCache: true
