agent_name: my_first_aea
author: open_aea
version: 0.1.0
description: A simple agent to demo the echo skill.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: QmaQRtL9NESStgoojt3oUkp8o1Xb9ZyhCmqhVBijYiBc7U
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.21.0:bafybeiht6b44da2wkfoajqcathf3zck5amsrbob27n2rwwbkkpknb22a5m
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeid5zr7hsoc6iabrx37hhgqjomlvbjpg3doisyeplbumfvazzybxaa
- fetchai/state_update:1.0.0:bafybeifchmbddn2cwad62eqaev3x4c2hqhw4jioh6gfn6iont2ocesjtf4
- open_aea/signing:1.0.0:bafybeieb4ohx5rboiwibfrtuis2eytlhuof6xq7zwwmmyz4cillzk2fvai
skills:
- fetchai/echo:0.19.0:bafybeihxayqoe6d6ztvjgj7odhw7xh22kcas47eq2fl4rknk3fcmmgia6e
default_connection: fetchai/stub:0.21.0
default_ledger: ethereum
required_ledgers:
- ethereum
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-ethereum:
    version: <2.0.0,>=1.0.0
