agent_name: gym_aea
author: open_aea
version: 0.1.0
description: The gym aea demos the interaction between a skill containing a RL agent
  and a gym connection.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/gym:0.19.0:QmecTP4XNr1PQ1ALatVfVHppRYWNp6mfWkGutXZcZ4pbq5
contracts: []
protocols:
- fetchai/default:1.0.0:QmYvdtdJLQhB8wH7PZUUASoPbCG7jXTPZRG9PKZ59wB9XV
- fetchai/gym:1.0.0:QmRVQSNkWbQTf5KkW3JTBZocrHooeNEwUPH9uMa9Afh9Kr
- fetchai/state_update:1.0.0:QmQyufe2zh8NMMf4qgBNFiLbj86iCERNBhfx5EroN9qPQy
- open_aea/signing:1.0.0:QmdrqznAYpnTWtLvLtLXiyMVr8PRfmj251puWbMZMNBw41
skills:
- fetchai/gym:0.20.0:QmVtLsMBRYngMkwos6giMNvxk6tZe3hb5chcS3Lkc5i7Fu
default_connection: fetchai/gym:0.19.0
default_ledger: ethereum
private_key_paths: {}
required_ledgers:
- ethereum
logging_config:
  disable_existing_loggers: false
  version: 1
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-ethereum:
    version: <2.0.0,>=1.0.0
