name: AEA framework sanity checks and tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  dependencies_checks:
    continue-on-error: False
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python_version: [3.8]
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install tox
        run : |
          pip install pip==21.2.4 --user
          pip install tox==3.15.1
      - name: Check Pipfile and tox.ini consistency
        run : |
          python ./scripts/check_pipfile_and_toxini.py
      - name: Install current aea
        run: |
          pip install -e .[all]
      - name: Check aea dependenices and imports
        run: |
          tox -e dependencies_check
